# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application (Update README.md)

on:
  push:
    branches: [ "main" ]
  schedule:
    # 매일 00시 (한국 시간 9시)에 실행됩니다.
    - cron: '0 0 * * *'

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Run Update Python Script
      run: |
        python util/updateVelog.py
    - name: Run Update README.md File
      run: |
        gut add .
        git diff
        git config --local user.email "qkddpgur318@gmail.com"
        git config --local user.name "YehyeokBang"
        git commit -m "Update README.md"
        git push
