# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application (Update README.md)

on:
  push:
    branches: ["main"]
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v3
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
      - name: Run Update Python Script
        run: |
          python updateREADME.py
      - name: Verify Changes in README.md
        id: check_diff
        run: |
          git diff --exit-code -- README.md
      - name: Run Update README.md File
        if: steps.check_diff.outputs.returncode != '0'
        run: |
          git add -f README.md
          git diff
          git config --local user.email "qkddpgur318@gmail.com"
          git config --local user.name "YehyeokBang"
          git commit -m "Update README.md"
          git push
